groups:
- description: null
  fields:
  - default: ''
    description: Set the container timezone with this (default is ``UTC``).
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: 1,31
    description: Set cron job interval to refresh feeds.
    id: CRON_MIN
    label: CRON_MIN
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
