name: nginxproxymanager
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:2.12.3
    ports:
    - protocol: tcp
      published: 80
      target: 80
    - protocol: tcp
      published: 443
      target: 443
    - protocol: tcp
      published: 81
      target: 81
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/data
      target: /data
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/etc/letsencrypt
      target: /etc/letsencrypt
      type: bind
