name: deluge
services:
  deluge:
    environment:
      DELUGE_LOGLEVEL: ${DELUGE_LOGLEVEL}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/deluge:2.2.0
    ports:
      - protocol: tcp
        published: 8112
        target: 8112
      - protocol: tcp
        published: 6881
        target: 6881
      - protocol: udp
        published: 6881
        target: 6881
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/config
        target: /config
        type: bind
      - source: ${CONTAINER_DATA_ROOT}/DATA
        target: /DATA
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
