name: alist
services:
  alist:
    image: xhofe/alist:v3.40.0
    ports:
      - protocol: tcp
        published: 5244
        target: 5244
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/data
        target: /opt/alist/data
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
