name: excalidraw
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - protocol: tcp
        published: 17638
        target: 80
    restart: 'unless-stopped'
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
