name: postgresql
services:
  postgresql:
    environment:
      PGID: ${PGID}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PUID: ${PUID}
      TZ: ${TZ}
    image: postgres:17.4
    ports:
    - protocol: tcp
      published: 5432
      target: 5432
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/data
      target: /var/lib/postgresql/data
      type: bind
