name: mineos-node
services:
  mineos:
    environment:
      SERVER_PORT: ${SERVER_PORT}
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      USER_UID: ${USER_UID}
      USE_HTTPS: ${USE_HTTPS}
    image: hexparrot/mineos:latest
    ports:
    - protocol: tcp
      published: 8444
      target: 8443
    volumes:
    - source: /var/games/mineos/minecraft
      target: /var/games/minecraft
      type: bind
