name: medusa
services:
  medusa:
    environment:
      TZ: ${TZ}
    image: pymedusa/medusa:master
    ports:
    - protocol: tcp
      published: 8081
      target: 8081
    volumes:
    - source: /AppData/$AppID
      target: /config
      type: bind
    - source: /AppData/$AppID/Downloads/Television
      target: /downloads
      type: bind
    - source: /AppData/$AppID/Media/Television
      target: /tv
      type: bind
