name: llama-factory-nvidia
services:
  llama-factory-nvidia:
    command:
    - llamafactory-cli
    - webui
    image: hiyouga/llamafactory:0.9.4
    ports:
    - protocol: tcp
      published: 18877
      target: 7860
