name: overseerr
services:
  overseerr:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/overseerr:1.33.2
    ports:
      - protocol: tcp
        published: 5055
        target: 5055
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/config
        target: /config
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
