groups:
- description: null
  fields:
  - default: '1000'
    description: ''
    id: GID
    label: GID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: Europe/Madrid
    description: ''
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: casaos
    description: ''
    id: PASSWORD
    label: PASSWORD
    required: false
    type: password
  - default: casaos
    description: ''
    id: USERNAME
    label: USERNAME
    required: false
    type: string
  id: authentication
  label: Authentication
- description: null
  fields:
  - default: '1000'
    description: ''
    id: UDI
    label: UDI
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
