groups:
- description: null
  fields:
  - default: $PGID
    description: Run Plex as specified gid.
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $PUID
    description: Run Plex as specified uid.
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  id: system
  label: System Settings
- description: null
  fields:
  - default: docker
    description: Let Docker handle the Plex Version
    id: VERSION
    label: VERSION
    required: false
    type: string
  - default: 'true'
    description: ''
    id: CPU_FALLBACK
    label: CPU_FALLBACK
    required: false
    type: string
  - default: all
    description: ''
    id: NVIDIA_VISIBLE_DEVICES
    label: NVIDIA_VISIBLE_DEVICES
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
