name: plex-nvidia
services:
  plex:
    environment:
      CPU_FALLBACK: ${CPU_FALLBACK}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
      PGID: ${PGID}
      PUID: ${PUID}
      VERSION: ${VERSION}
    image: lscr.io/linuxserver/plex:1.41.3
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/config
        target: /config
        type: bind
      - source: ${CONTAINER_DATA_ROOT}/Media
        target: /Media
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
