groups:
- description: null
  fields:
  - default: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
    description: ''
    id: DOCKER_MODS
    label: DOCKER_MODS
    required: false
    type: string
  id: configuration
  label: General Configuration
- description: null
  fields:
  - default: $PGID
    description: Run LazyLibrarian as specified GID
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $PUID
    description: Run LazyLibrarian as specified UID
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $TZ
    description: TimeZone
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
version: '1.0'
