name: downtify
services:
  downtify:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: ghcr.io/henriquesebastiao/downtify:1.1.1
    ports:
      - protocol: tcp
        published: 8582
        target: 8000
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/Downloads/downtify
        target: /downloads
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
