name: snapdrop
services:
  snapdrop:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/snapdrop:version-eac78009
    ports:
    - protocol: tcp
      published: 443
      target: 443
    - protocol: tcp
      published: 89
      target: 80
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
