groups:
- description: null
  fields:
  - default: $PGID
    description: ''
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $PUID
    description: ''
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $TZ
    description: timezone
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
version: '1.0'
