name: myspeed
services:
  myspeed:
    image: germannewsmaker/myspeed:1.0.9
    ports:
    - protocol: tcp
      published: 5216
      target: 5216
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/data
      target: /myspeed/data
      type: bind
