name: homeassistant
services:
  homeassistant:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: homeassistant/home-assistant:2025.7
    volumes:
    - source: /AppData/$AppID/config
      target: /config
      type: bind
    - read_only: true
      source: /etc/localtime
      target: /etc/localtime
      type: bind
    - read_only: true
      source: ${CONTAINER_DATA_ROOT}/run/dbus
      target: /run/dbus
      type: bind
