groups:
- description: null
  fields:
  - default: $TZ
    description: Time Zone Synchronization
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
version: '1.0'
