name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    ports:
      - protocol: tcp
        published: 10380
        target: 80
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/data
        target: /data
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
