name: autobrr
services:
  autobrr:
    environment:
      TZ: ${TZ}
    image: ghcr.io/autobrr/autobrr:v1.69.0
    ports:
      - protocol: tcp
        published: 7474
        target: 7474
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/config
        target: /config
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
