name: ollama
services:
  ollama:
    image: ollama/ollama:0.9.5
    ports:
    - protocol: tcp
      published: 11434
      target: 11434
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/
      target: /root/.ollama
      type: bind
