name: anythingllm
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    ports:
      - protocol: tcp
        published: 3051
        target: 3001
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/storage
        target: /app/server/storage
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
