name: autobrr
services:
  autobrr:
    environment:
      TZ: ${TZ}
    image: ghcr.io/autobrr/autobrr:v1.69.0
    ports:
    - protocol: tcp
      published: 7474
      target: 7474
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
