name: calibre-web
services:
  calibre-web:
    environment:
      DOCKER_MODS: ${DOCKER_MODS}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/calibre-web:0.6.24
    ports:
    - protocol: tcp
      published: 8083
      target: 8083
    volumes:
    - source: /AppData/$AppID/config
      target: /config
      type: bind
    - source: /Media/Books
      target: /books
      type: bind
