name: bazarr
services:
  bazarr:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/bazarr:1.5.3
    ports:
    - protocol: tcp
      published: 6767
      target: 6767
    volumes:
    - source: /Media/Movies
      target: /movies
      type: bind
    - source: /Media/TV Shows
      target: /tv
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
