name: grafana
services:
  grafana:
    image: grafana/grafana:11.5.2
    ports:
    - protocol: tcp
      published: 3003
      target: 3000
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/data
      target: /var/lib/grafana
      type: bind
