name: databag
services:
  databag:
    image: balzack/databag:0.1.18
    ports:
      - protocol: tcp
        published: 7000
        target: 7000
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/data
        target: /var/lib/databag
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
