name: pinchflat
services:
  pinchflat:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: ghcr.io/kieraneglin/pinchflat:latest
    ports:
    - protocol: tcp
      published: 8945
      target: 8945
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Media/Downloads
      target: /downloads
      type: bind
