name: open-webui-ollama
services:
  open-webui-ollama:
    environment:
      CPU_FALLBACK: ${CPU_FALLBACK}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
    image: ghcr.io/open-webui/open-webui:ollama
    ports:
    - protocol: tcp
      published: 3050
      target: 8080
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/open-webui
      target: /app/backend/data
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/ollama
      target: /root/.ollama
      type: bind
