name: hugo
services:
  hugo:
    command:
    - server
    - --bind=0.0.0.0
    image: ghcr.io/gohugoio/hugo:v0.148.2
    ports:
    - protocol: tcp
      published: 1313
      target: 1313
    volumes:
    - source: /AppData/$AppID/project
      target: /project
      type: bind
    - source: /AppData/$AppID/cache
      target: /cache
      type: bind
