name: petio
services:
  mongo:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: mongo:4.4.22
  petio:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: ghcr.io/petio-team/petio@sha256:1c5a9276a844f4284601cbe332905864950545ebdeaad74bacb9097ea4f4b333
    ports:
    - protocol: tcp
      published: 7777
      target: 7777
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /app/api/config
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/logs
      target: /app/logs
      type: bind
