name: duplicati
services:
  duplicati:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/duplicati:2.1.0
    ports:
    - protocol: tcp
      published: 8200
      target: 8200
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Duplicati/backups
      target: /backups
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Duplicati/source
      target: /source
      type: bind
