name: jdownloader2
services:
  jdownloader2:
    environment:
      GROUP_ID: ${GROUP_ID}
      JDOWNLOADER_HEADLESS: ${JDOWNLOADER_HEADLESS}
      MYJDOWNLOADER_DEVICE_NAME: ${MYJDOWNLOADER_DEVICE_NAME}
      MYJDOWNLOADER_EMAIL: ${MYJDOWNLOADER_EMAIL}
      MYJDOWNLOADER_PASSWORD: ${MYJDOWNLOADER_PASSWORD}
      TZ: ${TZ}
      USER_ID: ${USER_ID}
    image: jlesage/jdownloader-2:latest
    ports:
    - protocol: tcp
      published: 5800
      target: 5800
    - protocol: tcp
      published: 5900
      target: 5900
    - protocol: tcp
      published: 3129
      target: 3129
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
    - source: /Downloads
      target: /output
      type: bind
