name: openhab
services:
  openhab:
    environment:
      CRYPTO_POLICY: ${CRYPTO_POLICY}
      PGID: ${PGID}
      PUID: ${PUID}
    image: openhab/openhab:4.3.3
    restart: 'no'
    volumes:
    - read_only: true
      source: /etc/localtime
      target: /etc/localtime
      type: bind
    - read_only: true
      source: /etc/timezone
      target: /etc/timezone
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/addons
      target: /openhab/addons
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/conf
      target: /openhab/conf
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/userdata
      target: /openhab/userdata
      type: bind
