name: jellyfin
services:
  jellyfin:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/jellyfin:10.10.7
    ports:
    - protocol: tcp
      published: 8097
      target: 8096
    - protocol: tcp
      published: 8921
      target: 8920
    - protocol: tcp
      published: 7359
      target: 7359
    - protocol: tcp
      published: 1901
      target: 1900
    volumes:
    - source: /AppData/$AppID/config
      target: /config
      type: bind
    - source: /Media
      target: /Media
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/opt/vc/lib
      target: /opt/vc/lib
      type: bind
