name: ddns-go
services:
  ddns-go:
    image: jeessy/ddns-go:v6.13.2
    ports:
    - protocol: tcp
      published: 9876
      target: 9876
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /root
      type: bind
