name: medusa
services:
  medusa:
    environment:
      TZ: ${TZ}
    image: pymedusa/medusa:master
    ports:
      - protocol: tcp
        published: 8081
        target: 8081
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}
        target: /config
        type: bind
      - source: ${CONTAINER_DATA_ROOT}/Downloads/Television
        target: /downloads
        type: bind
      - source: ${CONTAINER_DATA_ROOT}/Media/Television
        target: /tv
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
