name: v2raya
services:
  v2raya:
    image: mzz2017/v2raya:v2.2.6.7
    volumes:
    - read_only: true
      source: ${CONTAINER_DATA_ROOT}/lib/modules
      target: /lib/modules
      type: bind
    - source: /etc/resolv.conf
      target: /etc/resolv.conf
      type: bind
    - source: /AppData/$AppID
      target: /etc/v2raya
      type: bind
