name: grafana
services:
  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - protocol: tcp
        published: 3003
        target: 3000
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/data
        target: /var/lib/grafana
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
