name: readarr
services:
  readarr:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/readarr:0.3.10-develop
    ports:
    - protocol: tcp
      published: 8787
      target: 8787
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Media/Books
      target: /books
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Downloads
      target: /downloads
      type: bind
