name: gateway-go
services:
  gateway-go:
    image: openiothub/gateway-go:v2.0.10
    ports:
    - protocol: tcp
      published: 34323
      target: 34323
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /root
      type: bind
