name: jackett
services:
  jackett:
    environment:
      AUTO_UPDATE: ${AUTO_UPDATE}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/jackett:0.22.1660
    ports:
      - protocol: tcp
        published: 9117
        target: 9117
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/config
        target: /config
        type: bind
      - source: ${CONTAINER_DATA_ROOT}/Downloads
        target: /downloads
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
