name: node-red
services:
  node-red:
    image: nodered/node-red:4.0.9-22
    ports:
    - protocol: tcp
      published: 1880
      target: 1880
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/data
      target: /data
      type: bind
