groups:
- description: null
  fields:
  - default: ChangeMeBy32KeyLengthOrGenerated
    description: Application Encryption Key
    id: APP_KEY
    label: APP_KEY
    required: false
    type: password
  - default: monicauser
    description: Database Username
    id: DB_USERNAME
    label: DB_USERNAME
    required: false
    type: string
  - default: monicasecret
    description: Database Password
    id: DB_PASSWORD
    label: DB_PASSWORD
    required: false
    type: password
  - default: 'True'
    description: Generate Random Root Password
    id: MARIADB_RANDOM_ROOT_PASSWORD
    label: MARIADB_RANDOM_ROOT_PASSWORD
    required: false
    type: password
  - default: monicauser
    description: Database User
    id: MARIADB_USER
    label: MARIADB_USER
    required: false
    type: string
  - default: monicasecret
    description: Database Password
    id: MARIADB_PASSWORD
    label: MARIADB_PASSWORD
    required: false
    type: password
  id: authentication
  label: Authentication
- description: null
  fields:
  - default: monica-db
    description: Database Host
    id: DB_HOST
    label: DB_HOST
    required: false
    type: string
  id: network
  label: Network Settings
- description: null
  fields:
  - default: monica
    description: Database Name
    id: MARIADB_DATABASE
    label: MARIADB_DATABASE
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
