groups:
- description: null
  fields:
  - default: $PGID
    description: Run Jellyfin as specified gid.
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $PUID
    description: Run Jellyfin as specified uid.
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $TZ
    description: TimeZone
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: 'true'
    description: ''
    id: CPU_FALLBACK
    label: CPU_FALLBACK
    required: false
    type: string
  - default: all
    description: ''
    id: NVIDIA_VISIBLE_DEVICES
    label: NVIDIA_VISIBLE_DEVICES
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
