name: sure
services:
  sure-db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:16
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/pgdata
      target: /var/lib/postgresql/data
      type: bind
  sure-redis:
    image: redis:8.2.1-alpine3.22
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/redis/data
      target: /data
      type: bind
  sure-web:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_ASSUME_SSL: ${RAILS_ASSUME_SSL}
      RAILS_FORCE_SSL: ${RAILS_FORCE_SSL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SELF_HOSTED: ${SELF_HOSTED}
    image: ghcr.io/we-promise/sure:0.6.3
    ports:
    - protocol: tcp
      published: 23000
      target: 3000
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/app/storage
      target: /rails/storage
      type: bind
  sure-worker:
    command:
    - bundle
    - exec
    - sidekiq
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_ASSUME_SSL: ${RAILS_ASSUME_SSL}
      RAILS_FORCE_SSL: ${RAILS_FORCE_SSL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SELF_HOSTED: ${SELF_HOSTED}
    image: ghcr.io/we-promise/sure:0.6.3
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/app/storage
      target: /rails/storage
      type: bind
