groups:
- description: null
  fields:
  - default: /opt
    description: ''
    id: EXEC_DIR
    label: EXEC_DIR
    required: false
    type: path
  id: storage
  label: Storage Configuration
- description: null
  fields:
  - default: '2222'
    description: ''
    id: PORT
    label: PORT
    max: 65535
    min: 1024
    required: false
    type: integer
  id: network
  label: Network Settings
- description: null
  fields:
  - default: login
    description: ''
    id: START_COMMAND
    label: START_COMMAND
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
