name: firefly
services:
  firefly:
    environment:
      FIREFLY_PASSWORD: ${FIREFLY_PASSWORD}
    image: uusec/firefly:latest
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/lib/modules
      target: /lib/modules
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/conf
      target: /firefly/conf
      type: bind
