name: flaresolverr
services:
  flaresolverr:
    environment:
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER}
      LOG_HTML: ${LOG_HTML}
      LOG_LEVEL: ${LOG_LEVEL}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: ${UMASK}
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.5
    ports:
      - protocol: tcp
        published: 8191
        target: 8191
    restart: 'unless-stopped'
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
