groups:
- description: null
  fields:
  - default: http://172.17.0.1:9993
    description: ZeroTier controller address
    id: ZT_ADDR
    label: ZT_ADDR
    required: false
    type: string
  - default: ztnet
    description: PostgreSQL Database Name
    id: POSTGRES_DB
    label: POSTGRES_DB
    required: false
    type: string
  - default: http://ztnet:3000
    description: Server-side URL for NEXTAUTH
    id: NEXTAUTH_URL_INTERNAL
    label: NEXTAUTH_URL_INTERNAL
    required: false
    type: string
  - default: ztnet
    description: PostgreSQL Database Name
    id: POSTGRES_DB
    label: POSTGRES_DB
    required: false
    type: string
  id: configuration
  label: General Configuration
- description: null
  fields:
  - default: ztnet-postgres
    description: PostgreSQL Host
    id: POSTGRES_HOST
    label: POSTGRES_HOST
    required: false
    type: string
  - default: '5432'
    description: PostgreSQL Port
    id: POSTGRES_PORT
    label: POSTGRES_PORT
    max: 65535
    min: 1024
    required: false
    type: integer
  - default: http://0.0.0.0:3050
    description: Canonical URL of your site
    id: NEXTAUTH_URL
    label: NEXTAUTH_URL
    required: false
    type: string
  id: network
  label: Network Settings
- description: null
  fields:
  - default: ztnet
    description: PostgreSQL User
    id: POSTGRES_USER
    label: POSTGRES_USER
    required: false
    type: string
  - default: ztnetbl5hbv98wl89x9v
    description: PostgreSQL Password
    id: POSTGRES_PASSWORD
    label: POSTGRES_PASSWORD
    required: false
    type: password
  - default: mn6vor005ncgnu9iuqxn8bg
    description: NextAuth Secret Key
    id: NEXTAUTH_SECRET
    label: NEXTAUTH_SECRET
    required: false
    type: password
  - default: ztnet
    description: PostgreSQL User
    id: POSTGRES_USER
    label: POSTGRES_USER
    required: false
    type: string
  - default: ztnetbl5hbv98wl89x9v
    description: PostgreSQL Password
    id: POSTGRES_PASSWORD
    label: POSTGRES_PASSWORD
    required: false
    type: password
  id: authentication
  label: Authentication
version: '1.0'
