groups:
- description: null
  fields:
  - default: $TZ
    description: TimeZone
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: 'false'
    description: ''
    id: N8N_SECURE_COOKIE
    label: N8N_SECURE_COOKIE
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
