name: radarr
services:
  radarr:
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: linuxserver/radarr:5.26.2
    ports:
    - protocol: tcp
      published: 7878
      target: 7878
    restart: 'no'
    volumes:
    - source: ${CONTAINER_DATA_ROOT}/config
      target: /config
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Media/Movies
      target: /movies
      type: bind
    - source: ${CONTAINER_DATA_ROOT}/Downloads
      target: /downloads
      type: bind
