name: cloudbeaver
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:25.2.5
    ports:
      - protocol: tcp
        published: 8978
        target: 8978
    restart: 'unless-stopped'
    volumes:
      - source: ${CONTAINER_DATA_ROOT}/workspace
        target: /opt/cloudbeaver/workspace
        type: bind
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
