groups:
- description: null
  fields:
  - default: '1000'
    description: ''
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: '1000'
    description: ''
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: Etc/UTC
    description: ''
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: subdomain1,subdomain2
    description: ''
    id: SUBDOMAINS
    label: SUBDOMAINS
    required: false
    type: string
  - default: ipv6
    description: ''
    id: UPDATE_IP
    label: UPDATE_IP
    required: false
    type: string
  - default: 'false'
    description: ''
    id: LOG_FILE
    label: LOG_FILE
    required: false
    type: string
  id: configuration
  label: General Configuration
- description: null
  fields:
  - default: token
    description: ''
    id: TOKEN
    label: TOKEN
    required: false
    type: password
  id: authentication
  label: Authentication
version: '1.0'
