groups:
- description: null
  fields:
  - default: $PGID
    description: Run qBittorrent as specified gid.
    id: PGID
    label: PGID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $PUID
    description: Run qBittorrent as specified uid.
    id: PUID
    label: PUID
    max: 65535
    min: 0
    required: false
    type: integer
  - default: $TZ
    description: TimeZone
    id: TZ
    label: TZ
    required: false
    type: string
  id: system
  label: System Settings
- description: null
  fields:
  - default: '002'
    description: Run qBittorrent as specified UMASK.
    id: UMASK
    label: UMASK
    required: false
    type: string
  id: configuration
  label: General Configuration
version: '1.0'
