name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
    - protocol: tcp
      published: 8080
      target: 8080
    volumes:
    - source: /AppData/Jenkins/data
      target: /data
      type: bind
    - source: /var/lib/docker/volumes/b098c98b2c5dec792246dc33375853c05958ace7c144f4aa157326a6f6c0de4c/_data
      target: /var/jenkins_home
      type: bind
